-   id: nbstripout
    name: nbstripout
    description: 'Strip output from Jupyter and IPython notebooks'
    entry: nbstripout 
    files: '*.ipynb'
    language: python
    language_version: python3
    require_serial: true
    types: [python]
